# Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

## create array using numpy
##create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [3]:
arr2 = np.arange(1,26).reshape(5,5)
print(arr2)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [10]:
print(arr2[0:2,0:2] * arr2[2:4,2:4])



[[ 44  28]
 [108 133]]


In [11]:
print(arr2[0,0]*arr2[3,3])

19


In [12]:
arr2[2][2]=44
print(arr2)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  44  14  15]
 [ 16  17  18  19  20]
 [ 21  22  23  24 100]]


In [ ]:
data = arr2[0:1,0:]
print(data)
print(data.shape)
new_data = np.append(data,[6,7,8])
print(new_data)
print(new_data.shape)
std = np.std(new_data)
print(std)
var = np.var(new_data)
print(var)



[[1 2 3 4 5]]
(1, 5)
[1 2 3 4 5 6 7 8]
(8,)
2.29128784747792
5.25


In [ ]:
### statistical concepts--Normalization
##to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)



Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)



Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [34]:
import numpy as np

arr = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])

# Get sorted unique values and their counts
unique_vals, counts = np.unique(arr, return_counts=True)
print(f"unique_vals: {unique_vals}")
print(f"counts: {counts}")
for vals,count in zip(unique_vals,counts):
    print(f"{vals} : {count}")

# Find the index of the highest count
max_count_index = np.argmax(counts)
print(f"max_count_index: {max_count_index}")


# Use the index to get the actual mode value
mode_value = unique_vals[max_count_index]

print(f"Mode: {mode_value}")


unique_vals: [1 2 3 4]
counts: [1 2 3 4]
1 : 1
2 : 2
3 : 3
4 : 4
max_count_index: 3
Mode: 4
